export const ADD_TODO = 'ADD_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const SET_EDITTING_ID = 'SET_EDITTING_ID'
export const RESET_EDITTING_ID = 'RESET_EDITTING_ID'
