export const ADD_TODO = 'ADD_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const SET_EDITTING_ID = 'SET_EDITTING_ID'
export const RESET_EDITTING_ID = 'RESET_EDITTING_ID'
export const TOGGLE_TODO_STATUS = 'TOGGLE_TODO_STATUS'

export const KILL_MONSTER = 'KILL_MONSTER'
export const ADD_MONSTER = 'ADD_MONSTER'
export const EDIT_NAME = 'EDIT_NAME'
export const CLEAR_ALL = 'CLEAR_ALL'

export const SUCCESS_GEN_RAN_NUM = 'SUCCESS_GEN_RAN_NUM'
export const FAIL_GEN_RAN_NUM = 'FAIL_GEN_RAN_NUM'